name: CI/CD Node.js - Générateur de citations avancé

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installation des dépendances
        run: npm install

      - name: Tests unitaires
        run: npm test

  deploy:
    name: Déploiement
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_GITHUB }}
          publish_branch: gh-pages
          publish_dir: ./src
